import type { ANYTHING } from '@flex-development/json'
import type { VercelRequest } from '@vercel/node'
import type { Logger } from 'pino'

/**
 * @file Type Definitions
 * @module lib/types
 */

/**
 * Shape of the API `req` object.
 */
export interface APIRequest extends VercelRequest {
  logger: Logger
  method: string
  path: string
  query: Record<string, ANYTHING>
  url: string
}

/**
 * Shape of `POST` requests sent to generate Apple Developer tokens.
 */
export interface CreateDeveloperTokenRequest extends APIRequest {
  /**
   * Basic Auth is used to retrieve Musickit identifiers and private keys.
   * All token generation requests must be authorized.
   */
  headers: Omit<APIRequest['headers'], 'authorization'> & {
    authorization: string
  }

  /**
   * Tokens can only be generated by sending `POST` requests.
   */
  method: 'POST' | 'post'

  /**
   * Additional information used to generate tokens.
   */
  query: CreateDeveloperTokenQuery
}

/**
 * Query parameters used to generate Apple Developer tokens.
 */
export type CreateDeveloperTokenQuery = {
  /**
   * Expiration time of registered claim key in seconds, whose value must not
   * exceed `15777000` (6 months in seconds).
   *
   * @default 15777000
   */
  expiresIn?: number

  /**
   * Apple Team ID.
   *
   * To locate your Team ID, sign in to your developer account, and click
   * Membership in the sidebar. Your Team ID appears in the Membership
   * Information section under the team name.
   */
  team: string
}
